services:

#< ----------------------- >

  edzespont_cache:

    hostname: repforge_cache

    build: ./cache/.

    # env_file:
    #   - ./envs/.uni.env

    volumes:
      - ./cache/conf:/usr/local/etc/redis:ro

    restart: always

#< ----------------------- >

  repforge_backend:

    hostname: repforge_backend2

    build: ./application/.

    volumes:
      - ./application/:/repforge_backend/:rw

    env_file:
      - ./envs/.repforge.env

    restart: always

    depends_on:
      repforge_mongo:
        condition: service_started


#< ----------------------- >

  repforge_mongo-express:

    hostname: repforge_mongo-express2

    #image: mongo-express
    image: mongo-express:1.0.2-20-alpine3.19

    restart: always

    env_file:
      - ./envs/.repforge.env

    # ports:
    #   - "32664:8081"

    depends_on:
      repforge_mongo:
        condition: service_started

#< ----------------------- >

  repforge_frontend:

    hostname: repforge_front_flask2

    build:
      context: ./frontend
      dockerfile: ./dockerfile

      args:
        VITE_API_BASE_URL: https://geer26.ddns.net/api

    restart: always

    env_file:
      - ./envs/.repforge.env

    depends_on:
      repforge_backend:
        condition: service_started


#< ----------------------- >

  proxy_certbot:

    hostname: repforge_proxy2

    build:
      context: ./proxy
      dockerfile: ./dockerfile

    ports:
      - "80:80"
      - "443:443"
      - "32665:32665"

    env_file:
      - ./envs/.repforge.env

    depends_on:
      repforge_frontend:
        condition: service_started

    restart: always

    volumes:
      - ./application/app/static:/static:ro
      - ./proxy/certs:/etc/letsencrypt:rw
      - ./proxy/conf:/etc/nginx/user_conf.d:ro
      - ./proxy/logs/:/var/log/nginx:rw