services:

#< ----------------------- >

  edzespont_cache:

    hostname: edzespont_cache

    build: ./cache/.

    # env_file:
    #   - ./envs/.uni.env

    volumes:
      - ./cache/conf:/usr/local/etc/redis:ro

    restart: no

#< ----------------------- >

#< ----------------------- >

  edzespont_frontend:

    container_name: edzespont_frontend

    hostname: edzespont_frontend

    build:
        context: ./frontend
        dockerfile: ./dockerfile.dev

    volumes:
        - ./frontend/:/app
        - /app/node_modules
        - ./frontend/node_modules:/app/node_modules

    restart: no

    ports:
        - "5173:5173"

    network_mode: "host"

#< ----------------------- >

  edzespont_db:
      image: postgres:18-alpine
      # Comment in production!
      ports:
        - "5432:5432"
      volumes:
        # - ./db/data:/var/lib/postgresql/data
        - ./db/data:/var/lib/postgresql/18/docker
        - ./db/init:/docker-entrypoint-initdb.d
      shm_size: 128mb
      environment:
        - POSTGRES_USER=geer26
        - POSTGRES_PASSWORD=726354Valami01?
        - POSTGRES_DB=edzespont


  adminer:
      image: adminer
      restart: no
      ports:
        - 8080:8080



#< ----------------------- >

  edzespont_backend:

    container_name: edzespont_backend

    hostname: edzespont_backend2

    build:
        context: ./backend
        dockerfile: ./dockerfile.dev

    volumes:
      - ./backend/:/edzespont_backend/:rw

    env_file:
      - ./envs/.dev_env

#    restart: always

    ports:
      - "5001:5001"

#    depends_on:
#      - repforge_cache
