FROM python:3.14-alpine
RUN apk update && apk add --no-cache g++ make libffi-dev musl-dev
RUN mkdir -p /edzespont_backend
WORKDIR /edzespont_backend
COPY requirements.txt /edzespont_backend
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt --no-cache-dir
RUN pip install --upgrade pip wheel setuptools requests
#CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "5001"]
CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "5001", "--reload"]
