"""add failed_login_attempt

Revision ID: 02dd14817bfb
Revises: f9f97a2122ea
Create Date: 2026-06-14 07:37:41.278792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02dd14817bfb'
down_revision: Union[str, Sequence[str], None] = 'f9f97a2122ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('failed_login_attempt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'failed_login_attempt')
    # ### end Alembic commands ###
