"""remove_testfield

Revision ID: 0d4ba1f55101
Revises: 1d0165b2fcad
Create Date: 2026-06-18 10:17:09.350476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4ba1f55101'
down_revision: Union[str, Sequence[str], None] = '1d0165b2fcad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'testfield')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('testfield', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
