"""test_add_simple_field

Revision ID: 1d0165b2fcad
Revises: b4ed7d67bc7e
Create Date: 2026-06-18 10:15:41.632384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0165b2fcad'
down_revision: Union[str, Sequence[str], None] = 'b4ed7d67bc7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('testfield', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'testfield')
    # ### end Alembic commands ###
