"""upd_models

Revision ID: 232e2601c18d
Revises: 95448b4b8b55
Create Date: 2026-06-15 17:38:23.884777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232e2601c18d'
down_revision: Union[str, Sequence[str], None] = '95448b4b8b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    op.drop_column('profiles', 'bio')
    # ### end Alembic commands ###
