"""add_city_to_profile

Revision ID: 74a4bb154667
Revises: 3f54d71fe1ba
Create Date: 2026-06-18 16:51:07.968750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a4bb154667'
down_revision: Union[str, Sequence[str], None] = '3f54d71fe1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'city')
    # ### end Alembic commands ###
