"""add_profile_table

Revision ID: a35e8c9ed856
Revises: 02dd14817bfb
Create Date: 2026-06-15 16:57:14.028390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35e8c9ed856'
down_revision: Union[str, Sequence[str], None] = '02dd14817bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'failed_login_attempt',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'failed_login_attempt',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
