"""add keyfp to user

Revision ID: f9f97a2122ea
Revises: 3b96d2d87510
Create Date: 2026-06-13 15:38:03.511279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f97a2122ea'
down_revision: Union[str, Sequence[str], None] = '3b96d2d87510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.String(), nullable=False))
    op.add_column('users', sa.Column('fingerprint', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fingerprint')
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###
